### PR TITLE
Add update tlc transient task to worker

### PR DESCRIPTION
**Pull request by canyousayyes**

### CODE REVIEW

**Comment by sfai05** [comment]
@canyousayyes reviewed

**Comment by canyousayyes** [comment]
Let's deploy!

**Comment by AnthonyTong** [comment]
Please remove me,  thanks
2015年10月19日 下午3:50 於 "Gene Ng" <notifications@github.com> 寫道：

**Comment by leonho** [comment]
@AnthonyTong that's pretty weird. you are not in any list. I will remove you from this pull request notification manually. hope it won't happen again.

**Comment by leonho** [comment]
@AnthonyTong I know what happened. This is a public repo. You can unsubscribe yourself from this repo by pressing Unwatch button at the top, thanks.

**Pull request merged**
